version: "3.9"
services:
  adboard:
    build: .
    image: python:adboard
    container_name: adboard.python
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./adboard:/app
    depends_on:
      - db
    links:
      - db:postgres
    command: >
      bash -c "python wait_for_postgres.py &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn adboard.wsgi -w 7 --bind 0.0.0.0:8000"
  db:
    image: postgres
    container_name: adboard.db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - .env
  nginx:
    build: ./nginx/
    image: nginx:adboard
    container_name: adboard.nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - adboard:adboard
    volumes:
      - ./adboard/media:/app/media
      - ./adboard/static:/app/static
      - ./nginx/letsencrypt:/etc/letsencrypt
