# Generated by Django 4.0.6 on 2022-07-14 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adboard_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=63, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='AdPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=127, verbose_name='title')),
                ('description', tinymce.models.HTMLField(max_length=8190, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (10, 'active'), (20, 'reserved'), (30, 'sold'), (90, 'canceled'), (99, 'removed')], db_index=True, default=0, verbose_name='status')),
                ('promoted', models.BooleanField(default=False, verbose_name='promoted')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='buyer')),
                ('category', models.ManyToManyField(related_name='ad_posts', to='adboard_site.category', verbose_name='categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_posts', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'advertisement post',
                'verbose_name_plural': 'advertisement posts',
                'ordering': ('-promoted', '-created_at'),
            },
        ),
    ]
