# Generated by Django 4.0.6 on 2022-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adboard_site', '0003_adpost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
    ]
