# Generated by Django 4.0.6 on 2022-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adboard_site', '0004_alter_adpost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'new'), (10, 'active'), (20, 'reserved'), (30, 'sold'), (90, 'cancelled'), (99, 'removed')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
